# Generated by Django 5.0.1 on 2024-02-01 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petitions', '0005_remove_petition_file_petition_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member_announcement_date', models.DateField()),
                ('debate_date', models.DateTimeField()),
                ('estimated_time', models.CharField(default='1시간', max_length=10)),
                ('debate_code_O', models.CharField(max_length=30)),
                ('debate_code_X', models.CharField(max_length=30)),
                ('petition_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petitions.petition')),
            ],
        ),
    ]
