# Generated by Django 5.0.1 on 2024-02-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_debate_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate_apply',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debate_apply',
            name='petition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debates.debate'),
        ),
    ]
