# Generated by Django 5.0.1 on 2024-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0004_alter_debate_apply_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate_apply',
            name='position',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
