# Generated by Django 5.0.1 on 2024-02-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0006_alter_debate_apply_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate_apply',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
