# Generated by Django 5.0.1 on 2024-02-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0008_alter_debate_apply_petition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate_apply',
            name='petition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debates.debate'),
        ),
    ]
