# Generated by Django 5.0.1 on 2024-02-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0011_debate_apply_raffle_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='member_announcement_date',
            field=models.DateTimeField(),
        ),
    ]
