# Generated by Django 5.0.1 on 2024-02-06 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0012_alter_debate_member_announcement_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate_Statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_type', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('is_chatgpt', models.BooleanField(default=False)),
                ('position', models.BooleanField(null=True)),
                ('debate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debates.debate')),
            ],
        ),
        migrations.CreateModel(
            name='Statement_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debates.debate_statement')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
