# Generated by Django 5.0.1 on 2024-01-31 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petition_Detail',
            fields=[
                ('BILL_NO', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('APPROVER', models.CharField(max_length=30)),
                ('CURR_COMMITTEE', models.CharField(max_length=30)),
                ('LINK_URL', models.CharField(max_length=255)),
                ('petition_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('BILL_NO', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petitions.petition_detail')),
                ('BILL_NAME', models.CharField(blank=True, max_length=100)),
                ('PROPOSER', models.CharField(blank=True, max_length=30)),
                ('PROPOSER_DT', models.DateField()),
                ('COMMITTEE_DT', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
