# Generated by Django 5.0.1 on 2024-01-31 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition_File',
            fields=[
                ('BILL_NO', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('petition_file', models.FileField(upload_to='')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='petition',
            name='content',
        ),
        migrations.RemoveField(
            model_name='petition_detail',
            name='petition_file',
        ),
        migrations.AlterField(
            model_name='petition',
            name='BILL_NO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petitions.petition_detail'),
        ),
        migrations.AddField(
            model_name='petition',
            name='file_bill_no',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='petitions.petition_file'),
            preserve_default=False,
        ),
    ]
