# Generated by Django 5.0.1 on 2024-01-31 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_petition_file_remove_petition_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='BILL_NO',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='petition',
            name='file_bill_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='petition_detail',
            name='BILL_NO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petitions.petition'),
        ),
        migrations.AlterField(
            model_name='petition_file',
            name='BILL_NO',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='petitions.petition'),
        ),
    ]
