# Generated by Django 5.0.1 on 2024-01-31 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_alter_petition_bill_no_alter_petition_file_bill_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='file_bill_no',
        ),
    ]
