# Generated by Django 5.0.1 on 2024-02-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_petition_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='petition_id',
        ),
    ]
